# Generated by Django 6.0.2 on 2026-02-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('run', 'Run'), ('walk', 'Walk'), ('hike', 'Hike'), ('bike', 'Bike'), ('moutain bike', 'Mountain Bike'), ('yoga', 'Yoga'), ('sport', 'Sport'), ('lift', 'Lift'), ('swim', 'Swim'), ('other', 'Other')], max_length=20),
        ),
    ]
