# Generated by Django 6.0.2 on 2026-02-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name_activity',
            field=models.CharField(default='Name of Activity', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Run', 'Run'), ('Walk', 'Walk'), ('Hike', 'Hike'), ('Bike', 'Bike'), ('Moutain Bike', 'Mountain Bike'), ('Yoga', 'Yoga'), ('Sport', 'Sport'), ('Lift', 'Lift'), ('Swim', 'Swim'), ('Other', 'Other')], max_length=20),
        ),
    ]
