# Generated by Django 6.0.2 on 2026-02-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_activity_name_activity_alter_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name_activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='name_of_activity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
