# Generated by Django 6.0.2 on 2026-02-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_activity_name_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('mi', 'Miles'), ('km', 'Kilometers'), ('m', 'Meters'), ('yd', 'Yards')], default='mi', max_length=5, null=True),
        ),
    ]
