# Generated by Django 6.0.2 on 2026-02-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_activity_distance_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('Miles', 'mi'), ('Kilometers', 'Km'), ('Meters', 'm'), ('Yards', 'yd')], default='mi', max_length=10, null=True),
        ),
    ]
