# Generated by Django 6.0.2 on 2026-04-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_activity_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='sleep_quality',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='stress',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='wellness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
